---
# tasks file for install_k8s_tools
- name: Install pre-reqs for k8s tools
  apt:
    name:
      - apt-transport-https
      - curl
    state: present

- name: Add Kubernetes apt-key
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

# Sleeping for 1 min to avoid an issue with updating repo cache
- name: Pausing for 1 minute
  pause:
    minutes: 1

- name: add Kubernetes APT repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: 'kubernetes'


# - shell: |
#     cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
#     deb https://apt.kubernetes.io/ kubernetes-xenial main
#     EOF

# - name: Update apt-get repo and cache
#   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Install k8s tools
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes

- shell: sudo apt-mark hold kubelet kubeadm kubectl